### ISSUE TITLE
New Project File

### ISSUE THREAD

**Issue by Roba42** [Roba42/MoCo-SS2023_Kraft_Koch_Zimmer#1]

**Comment by Roba42** [comment]
## Feature / Bug

Als Nutzer:in möchte ich [Aufgabe] mi dem Ziel [Zielzustand]. Falls [Fehler], dann möchte ich [Ausnahmezustand].

## Tasks

- [x] Task 1
- [x] Task 2
- [x] Task 3

**Comment by PhilippZimmer** [comment]
Alles Fertig
